# Generated by Django 5.1.4 on 2026-02-16 14:24

import apps.attendance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("devices", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Name (Arabic)",
                    ),
                ),
                (
                    "require_selfie",
                    models.BooleanField(
                        default=True,
                        help_text="Require a selfie photo during clock-in/out.",
                    ),
                ),
                (
                    "require_liveness",
                    models.BooleanField(
                        default=True,
                        help_text="Require liveness detection for biometric verification.",
                    ),
                ),
                (
                    "require_gps",
                    models.BooleanField(
                        default=True,
                        help_text="Require GPS coordinates during clock-in/out.",
                    ),
                ),
                (
                    "require_geofence",
                    models.BooleanField(
                        default=True,
                        help_text="Require employee to be within an assigned geofence.",
                    ),
                ),
                (
                    "require_wifi",
                    models.BooleanField(
                        default=False,
                        help_text="Require connection to a registered WiFi network.",
                    ),
                ),
                (
                    "require_device_registered",
                    models.BooleanField(
                        default=True,
                        help_text="Require the device to be registered for this employee.",
                    ),
                ),
                (
                    "max_offline_per_shift",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum offline attendance records allowed per shift.",
                    ),
                ),
                (
                    "allow_early_clockin_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Minutes before shift start that clock-in is allowed.",
                    ),
                ),
                (
                    "allow_late_clockout_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Minutes after shift end that clock-out is allowed.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Policy",
                "verbose_name_plural": "Attendance Policies",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(db_index=True)),
                ("clock_in_time", models.DateTimeField(blank=True, null=True)),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EARLY_DEPARTURE", "Early Departure"),
                            ("HALF_DAY", "Half Day"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        db_index=True,
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                (
                    "clock_in_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "clock_in_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "clock_out_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "clock_out_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "clock_in_selfie",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.attendance.models._tenant_selfie_upload_path,
                    ),
                ),
                (
                    "clock_out_selfie",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.attendance.models._tenant_selfie_upload_path,
                    ),
                ),
                (
                    "clock_in_wifi_ssid",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "clock_in_wifi_bssid",
                    models.CharField(blank=True, default="", max_length=17),
                ),
                (
                    "is_offline_record",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this record was created offline and synced later.",
                    ),
                ),
                (
                    "offline_integrity_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hash for verifying offline record integrity.",
                        max_length=64,
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the record has passed server-side validation.",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation error messages.",
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the record has been synced to the server.",
                    ),
                ),
                (
                    "liveness_passed",
                    models.BooleanField(
                        default=False, help_text="Whether liveness detection passed."
                    ),
                ),
                (
                    "face_match_score",
                    models.FloatField(
                        blank=True,
                        help_text="Face recognition match confidence score (0-1).",
                        null=True,
                    ),
                ),
                (
                    "gps_accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="GPS accuracy in meters as reported by the device.",
                        null=True,
                    ),
                ),
                (
                    "geofence_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the employee was within the assigned geofence.",
                    ),
                ),
                (
                    "wifi_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the WiFi network matched the policy.",
                    ),
                ),
                (
                    "device_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the device was registered for this employee.",
                    ),
                ),
                (
                    "clock_skew_detected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a significant clock skew was detected.",
                    ),
                ),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp reported by the client device.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "clock_in_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="devices.deviceregistry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="accounts.employee",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="attendance.attendancepolicy",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "-clock_in_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.TextField(
                        help_text="Employee's reason for requesting the correction."
                    ),
                ),
                (
                    "requested_clock_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="Corrected clock-in time requested by the employee.",
                        null=True,
                    ),
                ),
                (
                    "requested_clock_out",
                    models.DateTimeField(
                        blank=True,
                        help_text="Corrected clock-out time requested by the employee.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, default="", help_text="Notes from the reviewer."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="accounts.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Correction Request",
                "verbose_name_plural": "Attendance Correction Requests",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Name (Arabic)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Center latitude of the geofence.",
                        max_digits=10,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Center longitude of the geofence.",
                        max_digits=10,
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        help_text="Radius of the geofence in meters."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geofence",
                "verbose_name_plural": "Geofences",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.geofence",
            ),
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Name (Arabic)",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutes after shift start before marking as late.",
                    ),
                ),
                (
                    "is_overnight",
                    models.BooleanField(
                        default=False, help_text="Whether this shift spans midnight."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["name"],
                "abstract": False,
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="attendance.shift",
            ),
        ),
        migrations.CreateModel(
            name="WifiPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "ssid",
                    models.CharField(
                        help_text="WiFi network SSID (name).", max_length=100
                    ),
                ),
                (
                    "bssid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="WiFi access point BSSID (MAC address). Optional.",
                        max_length=17,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional geofence linked to this WiFi network.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wifi_policies",
                        to="attendance.geofence",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "WiFi Policy",
                "verbose_name_plural": "WiFi Policies",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["tenant", "date"], name="idx_attendance_tenant_date"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["employee", "date"], name="idx_attendance_employee_date"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["tenant", "employee", "date"],
                name="idx_attendance_tenant_emp_date",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["tenant", "status", "date"], name="idx_attendance_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["tenant", "date", "is_validated"],
                name="idx_attendance_validated",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["is_offline_record", "is_synced"],
                name="idx_attendance_offline_sync",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("tenant", "employee", "date", "shift")},
        ),
    ]
