# Generated by Django 5.1.4 on 2026-02-17 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Descriptive name for this token.', max_length=255)),
                ('token', models.CharField(db_index=True, help_text='Secret token value.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = allow all). E.g. ["10.0.0.1", "192.168.1.0/24"]')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Max requests per minute for this token.')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Integration Token',
                'verbose_name_plural': 'Integration Tokens',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Webhook delivery URL.')),
                ('secret', models.CharField(blank=True, default='', help_text='Secret for HMAC signature of webhook payloads.', max_length=128)),
                ('events', models.JSONField(default=list, help_text='List of event types to deliver. E.g. ["CLOCK_IN", "CLOCK_OUT"]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers to include with webhook delivery.')),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Configs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=30)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=10)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='tenants.tenant')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='integration.webhookconfig')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'event_type', 'status'], name='integration_tenant__28f86e_idx')],
            },
        ),
    ]
