# Generated by Django 5.1.4 on 2026-02-17 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('COMPANY', 'Company Device'), ('BYOD', 'Bring Your Own Device')], default='BYOD', max_length=10)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('device_identifier', models.CharField(help_text='Unique device identifier (Android ID or iOS Vendor ID).', max_length=255)),
                ('device_model', models.CharField(blank=True, default='', max_length=255)),
                ('device_manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('fcm_token', models.TextField(blank=True, default='', help_text='Firebase Cloud Messaging token for push notifications.')),
                ('is_rooted', models.BooleanField(default=False, help_text='Whether the device has been detected as rooted/jailbroken.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Approval'), ('REVOKED', 'Revoked'), ('REPLACED', 'Replaced')], db_index=True, default='PENDING', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Device Registry',
                'verbose_name_plural': 'Device Registries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('new_device_identifier', models.CharField(max_length=255)),
                ('new_device_model', models.CharField(blank=True, default='', max_length=255)),
                ('new_platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_change_requests', to='accounts.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('old_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_requests', to='devices.deviceregistry')),
            ],
            options={
                'verbose_name': 'Device Change Request',
                'verbose_name_plural': 'Device Change Requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='deviceregistry',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='devices_dev_tenant__e4f4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceregistry',
            index=models.Index(fields=['device_identifier'], name='devices_dev_device__77d6ae_idx'),
        ),
    ]
