# Generated by Django 5.1.4 on 2026-02-16 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encrypted_embedding",
                    models.BinaryField(
                        help_text="AES-256 encrypted face embedding vector."
                    ),
                ),
                (
                    "embedding_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number for embedding rotation support.",
                    ),
                ),
                (
                    "encryption_iv",
                    models.BinaryField(
                        help_text="Initialization vector used for AES encryption."
                    ),
                ),
                (
                    "num_images_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of images used to generate this embedding.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall quality score of the enrollment (0-1).",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_templates",
                        to="accounts.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Template",
                "verbose_name_plural": "Biometric Templates",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiometricEnrollmentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("STARTED", "Enrollment Started"),
                            ("IMAGE_CAPTURED", "Image Captured"),
                            ("LIVENESS_PASSED", "Liveness Passed"),
                            ("LIVENESS_FAILED", "Liveness Failed"),
                            ("EMBEDDING_GENERATED", "Embedding Generated"),
                            ("COMPLETED", "Enrollment Completed"),
                            ("FAILED", "Enrollment Failed"),
                            ("REVOKED", "Template Revoked"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_logs",
                        to="accounts.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_logs",
                        to="biometric.biometrictemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Enrollment Log",
                "verbose_name_plural": "Biometric Enrollment Logs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="biometrictemplate",
            index=models.Index(
                fields=["tenant", "employee", "status"],
                name="biometric_b_tenant__579496_idx",
            ),
        ),
    ]
